### PR TITLE
Fix: Fix reset not working

### LINKED ISSUE #3: `reset` does not work
reset 也无法正常工作

_Originally posted by @HiChen404 in https://github.com/jsun969/react-hook-form-antd/issues/2#issuecomment-1641280919_

### PR DESCRIPTION
**Pull request by avegatolber**
Close #3

### CODE REVIEW

File: src/FormItem.tsx [hunk 1]
```diff
@@ -24,6 +24,11 @@ export const FormItem = <TFieldValues extends FieldValues = FieldValues>({
   ...props
 }: FormItemProps<TFieldValues>) => {
   const { field, fieldState } = useController({ name, control, disabled });
+  const form = AntdForm.useFormInstance();
+
+  React.useEffect(() => {
```
Comment (jsun969) [inline src/FormItem.tsx:29]:
```suggestion
  useEffect(() => {
```

File: src/FormItem.tsx [hunk 2]
```diff
@@ -1,5 +1,5 @@
 import { Form as AntdForm } from 'antd';
-import type React from 'react';
+import React from 'react';
```
Comment (jsun969) [inline src/FormItem.tsx:2]:
```suggestion
import { useEffect } from 'react';
```

**Review by jsun969 — CHANGES_REQUESTED** [review]
thx for the contribution. Just a little suggestion for import.

File: src/FormItem.tsx (hunk 2 above)
Comment (avegatolber) [reply src/FormItem.tsx]: I just made a new commit with these changes

**Review by jsun969 — APPROVED** [review]
LGTM

**Comment by jsun969** [comment]
@all-contributors please add @avegatolber for code, bug
